In [2]:
import numpy as np

In [3]:
mylist = [1, 2, 3, 4, 5]
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3, 4, 5])

In [5]:
myarr = np.array(mylist)

In [6]:
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [14]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [15]:
len(np.linspace(0,10,3))

3

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand((5,5))


TypeError: 'tuple' object cannot be interpreted as an integer

In [18]:
np.random.rand(1)

array([0.94732335])

In [19]:
np.random.rand(4)

array([0.22278909, 0.5150462 , 0.73702027, 0.36355392])

In [20]:
np.random.rand(4,4)

array([[0.79810396, 0.65035868, 0.63636776, 0.71457582],
       [0.43104356, 0.26359186, 0.93211915, 0.43239177],
       [0.15265773, 0.76648787, 0.32355645, 0.40196186],
       [0.84583928, 0.74460358, 0.62852891, 0.17897577]])

In [21]:
np.random.randn(10)

array([ 0.06197409, -0.63402975, -0.77230976, -0.64296416, -1.97660459,
       -0.53935093,  1.64341864,  1.47073035,  0.85658042, -0.95808452])

In [22]:
np.random.randint((4,6))

array([0, 4])

In [23]:
np.random.randint(0, 101, (4,5))

array([[46, 22, 28, 53, 38],
       [97, 37, 51, 63, 44],
       [24, 68, 15, 77, 23],
       [37, 98, 19, 61, 24]])

In [26]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
arr = np.arange(0, 25)
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arr.max()

24

In [30]:
arr.argmax()

24

In [31]:
arr.argmin()

0

In [32]:
arr.min()

0

In [33]:
arr.dtype

dtype('int32')

In [34]:
arr.shape


(25,)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr.reshape(5,5).shape

(5, 5)

In [38]:
arr.reshape(25,1).shape

(25, 1)

In [39]:
arr = np.arange(0, 11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr[:5]

array([0, 1, 2, 3, 4])

In [45]:
arr[0:2:9]

array([0])

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[0:5] = 100

In [48]:
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [49]:
arr = np.arange(0, 11)

In [50]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
slice_of_array = arr[0:5]

In [52]:
slice_of_array

array([0, 1, 2, 3, 4])

In [53]:
slice_of_array[:] = 99


In [54]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [58]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [61]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr2d.shape

(3, 3)

In [63]:
arr2d[0]

array([ 5, 10, 15])

In [65]:
arr2d[1,1]

25

In [66]:
arr2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [67]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [69]:
bool_arr = arr > 4

In [70]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [71]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [72]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [74]:
arr - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [75]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [77]:
arr * 2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [79]:
arr / arr

C:\Users\Indrayudh\AppData\Local\Temp\ipykernel_11376\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [80]:
1/0

ZeroDivisionError: division by zero

In [81]:
1/arr

C:\Users\Indrayudh\AppData\Local\Temp\ipykernel_11376\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [82]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [83]:
np.log(arr)

C:\Users\Indrayudh\AppData\Local\Temp\ipykernel_11376\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [84]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr.sum()

45

In [86]:
arr.mean()

4.5

In [87]:
arr.max()

9

In [88]:
arr.var()

8.25

In [89]:
arr.std()

2.8722813232690143

In [90]:
2.8722 ** 2


8.249532839999999

In [92]:
arr2d = np.arange(0, 25).reshape(5,5)

In [95]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [96]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])